# Generated by Django 3.2.9 on 2021-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(default='123ABC', max_length=100)),
                ('placement', models.CharField(default='Träbro', max_length=200)),
                ('area', models.CharField(default='Mariehem', max_length=200)),
                ('city', models.CharField(default='Umeå', max_length=100)),
                ('x_cord', models.CharField(default='', max_length=40)),
                ('y_cord', models.CharField(default='', max_length=40)),
                ('masl', models.CharField(default='', max_length=20)),
                ('sensor_type', models.CharField(default='', max_length=40)),
                ('ref_system', models.CharField(default='', max_length=20)),
                ('has_simulations', models.BooleanField(default=False, max_length=200)),
                ('simul_path', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
