# Generated by Django 3.2.9 on 2021-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0013_rename_timestamp_sensor_time_value_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster_data',
            name='raster',
        ),
        migrations.AddField(
            model_name='raster_data',
            name='bl',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='raster_data',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='raster_data',
            name='tr',
            field=models.CharField(default='', max_length=20),
        ),
    ]
