# Generated by Django 3.2.9 on 2021-11-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raster_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(default='', max_length=20)),
                ('masl', models.CharField(default=0, max_length=10)),
                ('ref_system', models.CharField(default='', max_length=20)),
                ('img', models.CharField(default='', max_length=100)),
                ('tr', models.CharField(default='', max_length=20)),
                ('bl', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(default='123ABC', max_length=20)),
                ('masl', models.CharField(default='', max_length=20)),
                ('placement', models.CharField(default='Träbro', max_length=50)),
                ('area', models.CharField(default='Mariehem', max_length=50)),
                ('city', models.CharField(default='Umeå', max_length=30)),
                ('x_cord', models.CharField(default='', max_length=20)),
                ('y_cord', models.CharField(default='', max_length=20)),
                ('sensor_type', models.CharField(default='', max_length=40)),
                ('ref_system', models.CharField(default='', max_length=20)),
                ('has_simulations', models.BooleanField(default=False, max_length=10)),
                ('simul_path', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_time_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(default='', max_length=60)),
                ('masl', models.CharField(default='', max_length=20)),
                ('id_tag', models.CharField(default='123ABC', max_length=20)),
                ('time', models.DateTimeField()),
                ('placement', models.CharField(default='', max_length=50)),
                ('data_type', models.CharField(default='', max_length=20)),
                ('filtered', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
