# Generated by Django 3.2.9 on 2021-11-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='raster_data',
        ),
    ]
