# Generated by Django 3.2.9 on 2021-11-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0002_sensor_time_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_time_value',
            name='filtered',
            field=models.CharField(default='', max_length=20),
        ),
    ]
