# Generated by Django 3.2.9 on 2021-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0003_alter_sensor_time_value_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='area',
            field=models.CharField(default='Mariehem', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='city',
            field=models.CharField(default='Umeå', max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='has_simulations',
            field=models.BooleanField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_tag',
            field=models.CharField(default='123ABC', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='placement',
            field=models.CharField(default='Träbro', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='x_cord',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='y_cord',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor_time_value',
            name='id_tag',
            field=models.CharField(default='123ABC', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor_time_value',
            name='placement',
            field=models.CharField(default='', max_length=50),
        ),
    ]
