# Generated by Django 3.2.9 on 2021-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0003_raster_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='raster_data',
            name='img',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
