# Generated by Django 3.2.9 on 2021-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt_pg', '0004_auto_20211119_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sensor_time_value',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id_tag',
            field=models.CharField(default='123ABC', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor_time_value',
            name='row_id',
            field=models.CharField(default='', max_length=60, primary_key=True, serialize=False),
        ),
    ]
